document.writeln("    <div class=\'footer\'>");
document.writeln("      <div class=\'footerCon\'>");
document.writeln("        <p class=\'p1\'>This is heytea official website.</p>");
document.writeln("        <p class=\'p1\'>HEYTEA came into being in a lane named Jiangbianli , Guangdong in 2012. In this small store, we focused on creating drinks that we really love.</p>");
document.writeln("        <p class=\'p1\'>We wish a cup of good tea may inspire creative ideas. As more and more customers become our fan, we started to open branch stores.</p>");
document.writeln("        <p class=\'p1\'>We used to be known as ROYALTEA. Due to the failure to register the trademark, it is upgraded and registered as HEYTEA.</p>");
document.writeln("        <p class=\'p1\'>We are sorry that we do not accept brand franchise, and refuse to respond to related inquiries.</p>");
document.writeln("        <div class=\'footerDIvl clearfix\'>");
document.writeln("          <div class=\'erwemaCon\'>");
document.writeln("            <div class=\'l-erweima \'><img src=\'img/erweima.png\' />");
document.writeln("              <p>Follow us on Wechat</p>");
document.writeln("            </div>");
document.writeln("            <div class=\'r-erweima \'><img src=\'img/wbewm.png\' />");
document.writeln("              <p>Follow us on Webo</p>");
document.writeln("            </div>");
document.writeln("          </div>");
document.writeln("          <p class=\'p2\'>Follow us on Weibo/Wechat, receive our new product information & the news about Heytea in the first time. </p>");
document.writeln("          <p class=\'p2\'>If there is any problems, please contact us on Weibo/Wechat（@喜茶HEYTEA），we will resolve any issues as soon as possible.</p>");
document.writeln("        </div>");
document.writeln("        <div class=\'footerDIvr\'>");
document.writeln("          <p>SHENZHEN MEIXIXI CATERING MANAGEMENT CO.,LTD.</p>");
document.writeln("          <p>Address: 602C, Tower B, Aerospace Science And Technology Square, Nanshan District, Shenzhen</p>");
document.writeln("          <p>Contact：<span class='ntFont'>pr@heytea.com</span></p>");
document.writeln("          <p><img src=\'./img/1.png\' style=\'width:13px;height:13px;vertical-align:text-top;margin-right:5px;\' />粤公网安备：<a target=\'_blank\' style=\'color: #fff ;margin-top: 0 ;\' href=\'https://www.beian.gov.cn/portal/registerSystemInfo?recordcode=44030502001486\'>44030502001486号 </a></p>");
document.writeln("          <p>备案序号：<a target=\'_blank\' style=\'color: #fff ;margin-top: 0 ;\' href=\'http://www.miitbeian.gov.cn/\'>粤ICP备17015131号 </a></p>");
document.writeln("          <a id=\'_pingansec_bottomimagelarge_brand\' href=\'http://si.trustutn.org/info?sn=202170417028039221440&amp;certType=1\'><img src=\'http://v.trustutn.org/images/cert/brand_bottom_large.jpg\'></a>");
document.writeln("        </div>");
document.writeln("      </div>");
document.writeln("    </div>");
document.writeln("    <!--回到顶部-->");
document.writeln("    <div id=\'elevator_item\'>");
document.writeln("      <a id=\'elevator\' onclick=\'return false;\' title=\'回到顶部\'></a>");
document.writeln("      <a class=\'qr\'></a>");
document.writeln("      <div class=\'qr-popup\'>");
document.writeln("        <a class=\'code-link\'><img class=\'code\' src=\'img/wxewm.png\' /></a>");
document.writeln("        <span>关注喜茶HEYTEA</span>");
document.writeln("        <div class=\'arr\'></div>");
document.writeln("      </div>");
document.writeln("    </div>");